/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CallToAction: React.FC = () => {
  return (
    <div className="flex flex-col px-16 py-14 w-full bg-orange-500 rounded-3xl max-w-[1131px] mt-[4423px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-6xl font-semibold text-white leading-[70px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]">
        Learning focused on your goals with{" "}
        <span className="text-white">Maven House</span>
      </h2>
      <div className="flex flex-wrap gap-5 justify-between items-start mt-20 w-full text-base font-medium tracking-wide leading-loose text-white max-md:mt-10 max-md:max-w-full">
        <button className="flex gap-2 items-center self-start px-9 py-4 border border-white border-solid bg-white bg-opacity-0 rounded-[50px] max-md:px-5">
          <span className="self-stretch my-auto">
            Start Your Development Journey Now!
          </span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/82e5f78730830935a6dc874cf4bd87efbae252d2b05056dcaafb2d6478a2378c?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto aspect-square fill-white w-[13px]"
          />
        </button>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b2c748fdcee4794963f29aef40a9f0f33c4953c42b1e16be1e6ff3f6ecbaeae4?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f"
          alt=""
          className="object-contain shrink-0 self-end mt-10 w-9 aspect-square fill-white"
        />
      </div>
    </div>
  );
};

export default CallToAction;
