/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface CourseCardProps {
  title: string;
  instructor: string;
  rating: number;
  reviews: number;
  price: number;
  originalPrice: number;
  image: string;
  badge?: string;
}

const CourseCard: React.FC<CourseCardProps> = ({
  title,
  instructor,
  rating,
  reviews,
  price,
  originalPrice,
  image,
  badge,
}) => {
  return (
    <div className="flex flex-col w-[calc(33.333% - 1rem)] max-md:w-full">
      <div className="flex overflow-hidden flex-col justify-center self-stretch p-px rounded-lg border border-gray-300 border-solid bg-zinc-100">
        <img
          loading="lazy"
          src={image}
          alt={title}
          className="object-contain w-full aspect-[1.77]"
        />
      </div>
      <h3 className="mt-3 text-base font-bold leading-5 text-zinc-100">
        Web Development
      </h3>
      <p className="mt-2 text-xs leading-snug text-neutral-500">{instructor}</p>
      <div className="flex gap-1.5 mt-2.5 whitespace-nowrap">
        <span className="text-sm font-bold leading-tight text-amber-400">
          {rating}
        </span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fb8a9d12ace68cbcc49ef04fad51280c16984621ce14dd4b584153b86ae55c1f?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f"
          alt="Rating stars"
          className="object-contain shrink-0 self-start aspect-[5.68] w-[68px]"
        />
        <span className="text-xs leading-snug text-neutral-500">
          ({reviews})
        </span>
      </div>
      <div className="flex gap-3.5 mt-3.5 leading-none whitespace-nowrap">
        <span className="text-base font-bold text-zinc-100">₹{price}</span>
        <span className="text-sm text-neutral-500">₹{originalPrice}</span>
      </div>
      {badge && (
        <span className="px-2.5 py-2 mt-3.5 text-xs font-bold tracking-wide leading-tight text-center text-white bg-orange-500 rounded-md self-start">
          {badge}
        </span>
      )}
    </div>
  );
};

export default CourseCard;
