/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center pt-4 bg-neutral-800 pb-[500px] max-md:pb-24">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
