/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import ShoppingCart from "./ShoppingCart";
import RecommendedCourses from "./RecommendedCourses";
import CallToAction from "./CallToAction";

const ShoppingCartPage: React.FC = () => {
  return (
    <Layout>
      <ShoppingCart />
      <RecommendedCourses />
      <CallToAction />
    </Layout>
  );
};

export default ShoppingCartPage;
