/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CourseCard from "./CourseCard";

const recommendedCourses = [
  {
    id: 1,
    title: "Twitter Marketing & Twitter Ads For Beginners 2024",
    instructor: "Joshua George, ClickSlice Ltd",
    rating: 4.6,
    reviews: 326,
    price: 399,
    originalPrice: 3099,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0e9fbf660a114378f2e261c50fd014fb5d51c474d4ff7753933698a8e11fd315?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f",
  },
  {
    id: 2,
    title: "Twitter Marketing: How I Got 18.000 Followers in One",
    instructor: "Dan Silvestre",
    rating: 4.6,
    reviews: 213,
    price: 399,
    originalPrice: 1499,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/87458d6caee4d887a57d9e847e55185a7dfaaf2ef9949f35d686fa7108cff125?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f",
  },
  {
    id: 3,
    title: "Find your Following on Twitter",
    instructor: "Arvid Kahl",
    rating: 4.5,
    reviews: 148,
    price: 399,
    originalPrice: 2299,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c55822a8f39958b1303ef2f1fdbc3ff19142f42bf3d0c97078473c8105d76ab8?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f",
  },
  {
    id: 4,
    title: "ChatGPT for Viral Content Creation Social Media",
    instructor: "Jun Wu - Social Media Influencer",
    rating: 4.7,
    reviews: 161,
    price: 399,
    originalPrice: 799,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/525f48d24c0e5817525f43d95037aaafa79df80f5e4b70cf611d0b435941e224?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f",
    badge: "Bestseller",
  },
  {
    id: 5,
    title: "YouTube AI SEO Marketing and Ranking Masterclass for",
    instructor: "Jun Wu - Social Media Influencer",
    rating: 4.9,
    reviews: 441,
    price: 399,
    originalPrice: 2899,
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/dc648b4d0a84cf52863c007465fba44f7d74f25dba35b71f31eff9ee6f32c864?placeholderIfAbsent=true&apiKey=779eb5ea1637423490797e9103078d7f",
    badge: "Highest Rated",
  },
];

const RecommendedCourses: React.FC = () => {
  return (
    <section className="mt-14 w-full max-w-[1320px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-2xl font-bold leading-tight text-zinc-100">
        You might also like
      </h2>
      <div className="flex flex-wrap gap-5 mt-4">
        {recommendedCourses.map((course) => (
          <CourseCard key={course.id} {...course} />
        ))}
      </div>
    </section>
  );
};

export default RecommendedCourses;
