/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CourseItem from "./CourseItem";
import CartSummary from "./CartSummary";

const ShoppingCart: React.FC = () => {
  return (
    <section className="mt-16 w-full max-w-[1283px] max-md:mt-10 max-md:max-w-full">
      <h1 className="text-4xl font-bold leading-tight text-orange-500">
        Shopping Cart
      </h1>
      <p className="mt-9 text-base font-bold leading-tight text-zinc-100">
        1 Course in Cart
      </p>
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-9/12 max-md:ml-0 max-md:w-full">
          <CourseItem />
        </div>
        <CartSummary />
      </div>
    </section>
  );
};

export default ShoppingCart;
